name: Build site daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-diff:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      has_diff: ${{ steps.check-diff.outputs.has_diff }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - name: Check diff
        id: check-diff
        run: |
          pnpm run build
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected"
            git diff .
            echo "has_diff=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes"
            echo "has_diff=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: check-diff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    if: ${{ needs.check-diff.outputs.has_diff == 'true' }}
    environment: main
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node

      - uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1.11.3
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_SOTA1235_PR_EDITOR_APP_ID }}
          private-key: ${{ secrets.GH_APP_SOTA1235_PR_EDITOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            sota1235.github.io

      - name: Build site
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO: ${{ github.repository }}
        run: |
          pnpm run build
          DATE="$(date +%Y%m%d)"
          BRANCH_NAME="feat-build-site-daily-$DATE"

          # see: https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce#github-actionsbot
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "modify: build site daily(by GitHub Actions)"
          # TODO: post step to remove branch for duplication error
          git push origin "$BRANCH_NAME"
          gh pr create \
            -R "$REPO" \
            --title "[automation]build site daily - $DATE" \
            --body "build site daily" \
            --base main \
            --head "$BRANCH_NAME"
          PR_NUMBER="$(gh pr list -R "$REPO" --base main --head "$BRANCH_NAME" --json number --jq '.[0].number')"
          gh pr merge "$PR_NUMBER" -R "$REPO" --auto --merge
