name: Build site daily

on:
  schedule:
    - '0 0 * * *'
  workflow_dispatch:

jobs:
  check-diff:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - name: Check diff
        run: |
          pnpm run build
          if git diff --quiet .; then
            echo "No changes"
            echo "has_diff=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected"
            git diff .
            echo "has_diff=true" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: check-diff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.check-diff.outputs.has_diff == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - name: Build site
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          pnpm run build
          BRANCH_NAME="feat-build-site-daily-$(date +%Y%m%d)"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "modify: build site daily(by GitHub Actions)"
          git push origin "$BRANCH_NAME"
          gh pr create \
            -R "$REPO" \
            --title "[automation]build site daily - $(date +%Y%m%d)" \
            --body "build site daily" \
            --base main \
            --head "$BRANCH_NAME"
          PR_NUMBER="$(gh pr list -R $REPO --base main --head "$BRANCH_NAME" --json number --jq '.[0].number')"
          gh pr merge "$PR_NUMBER" --auto
