name: update-aqua-checksum
on:
  pull_request:
    paths:
      - aqua.yaml
      - aqua-checksums.json
      - .github/workflows/update-aqua-checksum.yaml

env:
  AQUA_LOG_COLOR: always

jobs:
  update-aqua-checksums:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 30
    steps:
      - name: Generate token (octo-sts)
        if: ${{ ! github.event.pull_request.head.repo.fork }}
        id: octo-sts
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        with:
          scope: ${{ github.repository }}
          identity: create_pull_request

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Install aqua
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.57.2
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token || github.token }}

      - name: Update checksum
        uses: aquaproj/update-checksum-action@c5df5a5c2a897a9b807068f062140506d092e7ac # v0.2.7
        with:
          prune: true
          skip_push: ${{ github.event.pull_request.head.repo.fork }}
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          AQUA_GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token || github.token }}
